---
name: "Pull Request CI"

on:
    push:
        branches: 
            - main

jobs:
    build:
        runs-on: "ubuntu-24.04"
        steps:
            - uses: actions/checkout@v4
            - name: run maven package
              run: mvn package
            - uses: actions/upload-artifact@v4
              with:
                name: spc-artifact
                path: target/*.jar
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                    **/surefire-reports/*.xml
            - name: SonarCloud Scan
              uses:  SonarSource/sonarcloud-github-action@v5.0.0
              with:
                organization: khajascicdsamples
                projectKey: spring-petclinic-apr25
                projectBaseDir: .
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}