---
name: "Pull Request CI"

on:
    push:
        branches: 
            - main
            - master

jobs:
    build:
        runs-on: "ubuntu-24.04"
        permissions:
          actions: read
          contents: read
          security-events: write
        steps:
            - uses: actions/checkout@v4
            - name: Cache local Maven repository
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven
            - name: Initialize Codeql
              uses: github/codeql-action/init@v3
              with:
                languages: java
            - name: run maven package
              run: mvn package
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
            
            
            - uses: actions/upload-artifact@v4
              with:
                name: spc-artifact
                path: target/*.jar
            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: |
                    **/surefire-reports/*.xml