---
name: "Pull Request CI"

on:
    push:
        branches: 
            - main

jobs:
    build:
        runs-on: "ubuntu-24.04"
        steps:
            - uses: actions/checkout@v4
            - name: run maven package
              run: mvn package
            - uses: actions/upload-artifact@v4
              with:
                name: spc-artifact
                path: target/*.jar